### ISSUE TITLE
Get cutadapt package into anaconda ipyrad channel

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#191]
Here's how to do it (have to do on both mac an linux if you want to push a new version):
```
## obv change this to the actual latest version
wget https://pypi.python.org/packages/47/bf/9045e90dac084a90aa2bb72c7d5aadefaea96a5776f445f5b5d9a7a2c78b/cutadapt-1.11.tar.gz#md5=8f8a8ef85b555ac07027c8c6e702b4af
tar -xvzf cutadapt*
cd cutadapt*
```
Edit the file `meta.yaml`:
```
package:
    name: cutadapt
    version: '1.11'
source:
    fn: cutadapt-1.11.tar.gz
    md5: 8f8a8ef85b555ac07027c8c6e702b4af
    url: https://pypi.python.org/packages/47/bf/9045e90dac084a90aa2bb72c7d5aadefaea96a5776f445f5b5d9a7a2c78b/cutadapt-1.11.tar.gz
build:
    number: '0'
    script: $PYTHON setup.py install
    skip: 'False'
requirements:
    build:
        - python
    run:
        - python
test:
    commands:
        - cutadapt --version > /dev/null
    imports:
        - cutadapt
        - cutadapt.scripts
about:
    home: https://cutadapt.readthedocs.io/
    license: MIT License
    summary: trim adapters from high-throughput sequencing reads
```

`conda build .`

My conda build is already set up to push to ipyrad anaconda channel automatically, but if yours isn't then you'll have to do this byhand (with the `ipyrad` user and the super secret password).

**Comment by isaacovercast** [comment]
Also, for the benefit of `conda build` you need to add the ipyrad channel like so:

`conda config --add channels ipyrad`

**Comment by isaacovercast** [comment]
For v 1.12 it pulls in `xopen`, so you have to do this song and dance to get xopen added to the ipyrad channel. Get the pypi package from here: https://pypi.python.org/pypi/xopen

```
package:
    name: xopen
    version: '0.1.1'
source:
    fn: xopen-0.1.1.tar.gz
    md5: 4e0e955546ee6bee4ea736b54623a671
    url: https://pypi.python.org/packages/9a/b7/8906d6b2c4f874c0aacc676709a3d533362ac93bebc4a656c9df19421c9b/xopen-0.1.1.tar.gz#md5=4e0e955546ee6bee4ea736b54623a671
build:
    number: '0'
    script: $PYTHON setup.py install
    skip: 'False'
requirements:
    build:
        - python
    run:
        - python
test:
    commands:
        - xopen --version > /dev/null
about:
    home: https://pypi.python.org/pypi/xopen
    license: MIT License
    summary: Open compressed files transparently
```
